In [8]:
import pandas as pd
csv = pd.read_csv('candy-data.csv')

In [9]:
csv

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,chocolate-prediction,win-prediction
0,100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,0,0.5801
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,0,0.2483
2,One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,1,0.5098
3,One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,1,0.7404
4,Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,1,0.4046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Twizzlers,0,1,0,0,0,0,0,0,0,0.220,0.116,45.466282,1,0.4665
81,Warheads,0,1,0,0,0,0,1,0,0,0.093,0.116,39.011898,1,0.1150
82,WelchÕs Fruit Snacks,0,1,0,0,0,0,0,0,1,0.313,0.313,44.375519,0,0.0420
83,WertherÕs Original Caramel,0,0,1,0,0,0,1,0,0,0.186,0.267,41.904308,1,0.3234
84,Whoppers,1,0,0,0,0,1,0,0,1,0.872,0.848,49.524113,1,0.6296

In [10]:
#convert winpercent to decimal
csv['winpercent'] = csv['winpercent'] / 100
#mse error 
from sklearn.metrics import mean_squared_error
mse_win_percent = mean_squared_error(csv['winpercent'], csv['win-prediction'])
print("win percent mse error: ", mse_win_percent)
#mse error chocolate prdiction
mse_chocolate = mean_squared_error(csv['chocolate'], csv['chocolate-prediction'])
print("chocolate mse error: ", mse_chocolate)

win percent mse error:  0.09028975691020778
chocolate mse error:  0.5176470588235295